# paths and files
tandemx_dir: '/media/maffe/nvme/Tandem-X-EDEM/'
oggm_dir: '/home/maffe/OGGM/'
coastlines_gshhg_dir: '/media/maffe/nvme/gshhg/'
racmo_dir: '/media/maffe/nvme/racmo/'
ERA5_t2m_dir: '/media/maffe/nvme/ERA5/'

millan_velocity_dir: '/media/maffe/nvme/Millan/velocity/'
NSIDC_velocity_Greenland_dir: '/media/maffe/nvme/Greenland_NSIDC/velocity/'
NSIDC_velocity_Antarctica_dir: '/media/maffe/nvme/Antarctica_NSIDC/velocity/NSIDC-0754/'

millan_icethickness_dir: '/media/maffe/nvme/Millan/thickness/'
farinotti_icethickness_dir: '/media/maffe/nvme/Farinotti/composite_thickness_RGI60-all_regions/'
NSIDC_icethickness_Greenland_dir: '/media/maffe/nvme/Greenland_NSIDC/thickness/' # BedMachine_v5
NSIDC_icethickness_Antarctica_dir: '/media/maffe/nvme/Antarctica_NSIDC/thickness/NSIDC-0756/' # BedMachine v3

model_input_dir: '/home/maffe/PycharmProjects/iceboost/saved_iceboost/'
model_output_results_dir: '/home/maffe/PycharmProjects/iceboost/saved_iceboost/iceboost_deploy_xgb_cat_20240731_k3/'
model_output_global_deploy_dir: '/media/maffe/nvme/iceboost_global_deploy/'
model_filename_xgb: 'iceboost_xgb_20240731.json'
model_filename_cat: 'iceboost_cat_20240731.cbm'
filename_csv_deploy: 'iceboost_deploy_list_id.csv'
metadata_csv_file: '/media/maffe/nvme/glathida/glathida-3.1.0/glathida-3.1.0/data/metadata35_hmineq0.0_tmin20050000_mean_grid_100.csv'

# save model
save_model: 0

# model deploy save figures
deploy_save_figs: 0

# configs for feature fetching
graph_max_layer_depth: 3 # maximum depth consider in the graph used to calculate the glacier cluster
kdtree_dist_max_k_geometries: 99999 # maximum number of geometries considered in dist method.

# configs for model inference
featuresBase: &base ['Area', 'Perimeter', 'Zmin', 'Zmax', 'Zmed', 'Slope', 'Lmax', 'Aspect', 'TermType',
                     'elevation', 'elevation_from_zmin', 'dist_from_border_km_geom',
                     'slope50', 'slope75', 'slope100', 'slope125', 'slope150', 'slope300', 'slope450', 'slopegfa',
                     'curv_50', 'curv_300', 'curv_gfa', 'dmdtda_hugo', 'deltaZ',
                     'smb', 't2m', 'dist_from_ocean']

featuresVel: &vel ['v50', 'v100', 'v150', 'v300', 'v450', 'vgfa']

features:
    - *base
    - *vel
n_points_regression: 30000
target: 'THICKNESS'
millan: 'ith_m'
farinotti: 'ith_f'